#!/usr/bin/env bash
set -e

deps=(jq gum)

for dep in "${deps[@]}"; do
    type -p "${dep}" > /dev/null || { >&2 echo "gh prx: missing dep: ${dep}"; exit 1; }
done

choices=$(gh pr list "${@}" --json author,title,number | jq -r '.[] | "#\(.number): \(.title) (@\(.author.login))"')

# No PRs open, nothing to do.
[[ -z "${choices}" ]] && exit 0

choice=$(gum choose --header="Select PR:" <<< "${choices}" | cut -d' ' -f1 | tr -d '#:')

[[ -z "${choice}" ]] && exit 0

gh pr checkout "${choice}"
